version: 3
endpoint: http://localhost:8081
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
seeds_directory: hasura/seeds
admin_secret: myadminsecretkey
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
