service: tfm4-worker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0

functions:
  hello:
    handler: dist/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  computeAvailability:
    handler: dist/availability/compute.computeAvailability
    events:
      - httpApi:
          path: /availability/compute
          method: post
