service: tfm4-worker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0

functions:
  hello:
    handler: dist/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  # AVAILABILITY
  computeAvailability:
    handler: dist/availability/compute.computeAvailability
    events:
      - httpApi:
          path: /availability/compute
          method: post

 # RESERVATION
  getReservationByDay:
    handler: dist/reservation/get-by-day.getReservationByDay
    events:
      - httpApi:
          path: restaurant/{restaurantId}/reservation/{day}
          method: get

  create:
    handler: dist/reservation/create.handler
    events:
      - httpApi:
          path: /reservation/create
          method: post
