service: tfm4-worker
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  example:
    handler: src/example.exampleAction
    events:
      - httpApi:
          path: /example
          method: post

  computeAvailability:
    handler: src/availability/compute.computeAvailability
    events:
      - httpApi:
          path: /availability/compute
          method: post
